### ISSUE TITLE
Canali non funzionanti lista regionali

### ISSUE THREAD

**Issue by Angeloblu83** [WorldLiveTV/WorldLiveTV.github.io#10]
Segnalo problemi sulla lista canali regionali i seguenti canali : video33 (vb33) trentino , video mediterraneo(Sicilia), video star (Sicilia)

**Comment by Angeloblu83** [comment]
Preciso anche come già segnalato qualche giorno fa di aggiungere nei regionali tele campione sport presente live streaming sul sito publirose

**Comment by pandvan** [comment]
> video33 (vb33) trentino , video mediterraneo(Sicilia), video star (Sicilia)

Grazie per la segnalzione.
I link agli stream sono stati aggiornati. A breve saranno visibili con WLTV.

**Comment by Angeloblu83** [comment]
Non funzionanti retesole Umbria e Lazio

**Comment by pandvan** [comment]
@Angeloblu83 potresti condividere la pagina dove sono disponibil gli stream di questi due canali?

**Comment by Angeloblu83** [comment]
> @Angeloblu83 potresti condividere la pagina dove sono disponibil gli stream di questi due canali?

Ti lascio quello di retesole Lazio che poi e' lo stesso streaming di retesole Umbria 
https://www.retesole.it/streaming-lazio/

**Comment by Angeloblu83** [comment]
Ti aggiungo anche la diretta streaming di Campione sport che manca nei regionali Lombardia casomai se la volete aggiungere li anche solo provvisoriamente 
https://www.publirose.it/diretta-campionesport/

**Comment by pandvan** [comment]
> retesole Lazio che poi e' lo stesso streaming di retesole Umbria
Link allo stream aggiornato.
A breve sarà disponibile anche tramite add-on.

**Comment by pandvan** [comment]
> Campione sport che manca nei regionali Lombardia

Aggiunto.
Grazie della segnalazione.
