### ISSUE TITLE
Regionali 

### ISSUE THREAD

**Issue by Angeloblu83** [WorldLiveTV/WorldLiveTV.github.io#11]
Segnalo nuovo link per teleroma 56 ora trasmettono da twitch ihttps://www.twitch.tv/teleroma_56/

**Comment by pandvan** [comment]
Si tratta di un canale visibile mediante DTT?
La diretta su Twhich non è nemmeno h24. Questo andrebbe contro le politiche del progetto.

**Comment by Angeloblu83** [comment]
Video33hd andrebbe ricontrollato da problemi durante la riproduzione dopo un paio di minuti che e' in play provato da altre fonti (TV dream) tutto fluido stessa diretta forse qualche problema a livello player

**Comment by pandvan** [comment]
> Segnalo nuovo link per teleroma 56

Aggiunto
