### ISSUE TITLE
Canali non funzionanti da aggiornare

### ISSUE THREAD

**Issue by Angeloblu83** [WorldLiveTV/WorldLiveTV.github.io#12]
Segnalo da aggiornare attualmente non funzionante su wltv ma sito ok Promovideotv.

**Comment by Angeloblu83** [comment]
Mediterranea TV (puglia) sembra che ora trasmette con dituttochannel  da controllare lascio link del sito ufficiale https://www.mediterraneatv.it/mediterranea-tv-ditutto-it-channel/

**Comment by pandvan** [comment]
> Promovideotv

Link dello stream aggiornato. A breve sarà disponibile sull'add-on

**Comment by Angeloblu83** [comment]
Di tutto channel ti confermo e' una canale diverso anche esso in streaming dalla Puglia e' in partnership con mediterranea se vedi hanno inserito entrambe le dirette sul sito di mediterranea si potrebbe aggiungerlo sempre sulla lista regionali Puglia

**Comment by pandvan** [comment]
Meditteranea TV non sta più nel DTT e sembra che trasmetta solo via Internet, niente etere.
Sulla carta sarebbe da sezione "vari" ma avendo un contenuto che immagino sia prettamente localizzato, potrebbe andare anche su lista regionali.

Indipendetemente da quale sarà la scelta, grazie per la segnalazione.

**Comment by pandvan** [comment]
> Di tutto channel

Aggiunto, per ora tra i regionali nella Puglia.

**Comment by pandvan** [comment]
> Tele universo

Link aggiornato.
Grazie per la segnalazione.

**Comment by pandvan** [comment]
Su Telegram l'utente "Giuseppe" segnala

> Potete ripristinare telespazio Messina?

**Comment by Angeloblu83** [comment]
Da ripristinare tele spazio Messina 
riporto il link funzionante segnalatoci da un utente nel gruppo https://www.telespazioplay.com

**Comment by pandvan** [comment]
> Potete ripristinare telespazio Messina?

Link aggiornato.
