### ISSUE TITLE
Canali Sportitalia

### ISSUE THREAD

**Issue by Angeloblu83** [WorldLiveTV/WorldLiveTV.github.io#13]
Segnalo problema relativo ai canali live di Sportitalia per ora funzionanti solo tramite la loro app ufficiale da ricercare una soluzione

**Comment by CrAcK75** [comment]
Si riprenderanno quando saranno nuovamente disponibili sul sito

**Comment by pandvan** [comment]
Al prossimo aggiornamento di WLTV saranno nuovamente disponibili.
