### ISSUE TITLE
Nuovo canale rai (rai radio 2 ) non funzionante

### ISSUE THREAD

**Issue by Angeloblu83** [WorldLiveTV/WorldLiveTV.github.io#14]
Segnalo da sistemare appena possibile il nuovo canale Rai radio 2 alla posizione 202

**Comment by infid0** [comment]
Noto che non è stato ancora stato fixato giusto? Potete metterci una pezza con il link ufficiale: 
`https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=5674080&output=16`
Funziona bene ovunque tranne che su VLC, ma visto che verrà usato su Kodi direi chi se ne frega. :3

**Comment by pandvan** [comment]
Il canale _Rai Radio 2 Visual Radio_ è stato aggiunto a WLTV
Lo trovate al numero 202 come da LCN DTT (e anche Tivusat)
