### ISSUE TITLE
Due canali non funzionanti e uno nuovo.

### ISSUE THREAD

**Issue by infid0** [WorldLiveTV/WorldLiveTV.github.io#15]
`Boing Plus` non funziona e `Sportitalia Motori` non esiste più da un pezzo. Le dirette disponibili sono: `Sportitalia`, `Sportitalia Solocalcio` e `Sportitalia Live 24`. Inoltre vorrei segnalare la comparsa di `RTL 102.5 News` sul canale 233. 
`https://dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S38122967/2lyQRIAAGgRR/playlist_video.m3u8`
Grazie mille! :3

Edit: Ho notato che tra i canali del DVB-T manca anche `Radio ZETA` canale 266. 
`https://dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S9346184/XEx1LqlYbNic/playlist_video.m3u8`

**Comment by infid0** [comment]
A proposito di Sportitalia... Di recente hanno aggiornato il sito e con l'occasione gli streaming delle dirette. Attualmente questi sono i nuovi indirizzi: 
SI: `https://di-g7ij0rwh.vo.lswcdn.net/sportitalia/sihd/playlist.m3u8`
SI Solocalcio: `https://di-g7ij0rwh.vo.lswcdn.net/sportitalia/sisolocalcio.smil/playlist.m3u8`
SI Live24: `https://di-g7ij0rwh.vo.lswcdn.net/sportitalia/silive24.smil/playlist.m3u8`
Anche RDS Social TV ha aggiornato lo streaming, questo è il suo indirizzo: 
`https://stream.rdstv.radio/index.m3u8`
Spero vi torni utile, alla prossima! :3

**Comment by pandvan** [comment]
> `Boing Plus` 

Grazie per la segnalazione.
@CrAcK75 idee?

> `Sportitalia Motori` 

Rimosso

> `RTL 102.5 News` 

Aggiunto

> `Radio ZETA` 

Aggiunto

> Sportitalia... Di recente hanno aggiornato il sito e con l'occasione gli streaming delle dirette. 

Effettuate modifiche al add-on che tengono conto del nuovo sito.

> RDS Social TV ha aggiornato lo streaming

Ne usiamo uno leggermente diverso perché i _cialtroni_ sbagliano ad indicare il bitrate di alcuni flussi.
Questo  comporta che il player sceglie in automatico il flusso 720p in quanto "ingannato" dai metadati che lo danno con un bitrate maggiore del flusso 1080p.
WLTV forza invece l'uso dello stream 1080p.

> Spero vi torni utile

Sì, molto.
Grazie per le segnalazioni.

**Comment by infid0** [comment]
> WLTV forza invece l'uso dello stream 1080p.

Scusa l'off topic, ma visto che ci siamo ne approfitto. In WLTV c'è un opzione per ridurre la qualità del video a 720p, o meglio ancora in automatico? Il problema è che ho una connessione pietosa e con certi canali purtroppo mi va in buffering ogni X secondi. :/
Grazie in anticipo! :3

**Comment by pandvan** [comment]
> WLTV c'è un opzione per ridurre la qualità del video a 720p, o meglio ancora in automatico

Apro e chiudo off-topic.
Kodi non fa transcodica, quindi possiamo mettere in play solo quello che offrono le emittenti.
Nel caso lo stream contenga più flussi, dipende se questi sono dati in pasto direttamente a Kodi oppure passando per Inputstream Adaptive. La scelta dipende dal tipo di flusso, ad esempio se è protetto da DRM Widevine, è obbligo usare Inputstream Adaptive.

Se la riproduzione avviene direttamente, dalle opzioni video di Kodi durante la riproduzione dovrebbe essere possibile selezionare la traccia video preferita. Non mi risulta sia possibile impostare una soglia o altre logiche.

Se la riproduzione avviene passando per Inputstream Adaptive, è possibile modificare la sua configurazione per impostare un tetto massimo di banda e quindi andando a selezionare, se disponibile, un flusso a risoluzione minore che non supera il bitrate impostato.

Per ulteriori indicazioni, ti consiglio di passare nel gruppo telegram dedicato a WLTV o Kodi Italia.

**Comment by philbel66** [comment]
Salve, qualcuno mi potrebbe trovare l'indirizzio du RTL 102.5 PLUS ? (canal dietro le quinte...)
Grazie mille

**Comment by infid0** [comment]
> Salve, qualcuno mi potrebbe trovare l'indirizzio du RTL 102.5 PLUS ? (canal dietro le quinte...) Grazie mille

Ciao, eccoti il link: 
`https://dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S26743519/49ksH8apMKou/playlist.m3u8`
Buona serata! :3

**Comment by philbel66** [comment]
Grazie mille
E quello di RTL 102.5 versione “normale” ?

**Comment by CrAcK75** [comment]
> Grazie mille E quello di RTL 102.5 versione “normale” ?

scusami ... questo non è un forum spaccio link quindi finiamola
