### ISSUE TITLE
Class CNBC - Canale

### ISSUE THREAD

**Issue by Reneee69** [WorldLiveTV/WorldLiveTV.github.io#16]
Ciao ,
non saprei se c'è da qualche parte o se aggiungerlo alla lista 
Canale Class Cnbc adesso trasmette su sky canale 507
il link dovrebbe essere questo:

https://streamcdng14-859c1818ed614cc5b0047439470927b0.msvdn.net/live/S76890577/tDoFkZD3T1Lw/playlist.m3u8

**Comment by pandvan** [comment]
Hai idea se è lo stesso canale trasmesso su Tivusat al numero 81 con identificativo CNBC HD?
Se è necessario abbonamento Sky andrebbe piazzato in lista "vari".

Grazie per la segnalazione.

**Comment by Reneee69** [comment]
mi sa che c'è già trovato al numero 890 su lista dtt

**Comment by Reneee69** [comment]
quel link è lo streaming ufficiale sul sito web di clascnbc

**Comment by pandvan** [comment]
Dopo alcune verifiche abbiamo constatato che Class CNBC e CNBC HD sono 2 canali distinti.
Class CNBC è disponibile solo nel bouquet Sky e dovrebbe essere visibile anche _senza_ abbsonamento attivo, serve però un ricevitore SAT di Sky.
Per il momento non servono dunque modifiche. Per quanto mi riguarda, sarei dell'idea di spostare quello che non sta su LCN DTT e LCN Tivusat sulla lista Vari, ma al momento non è previsto.
