### ISSUE TITLE
[Richiesta] Aggiunta radio FM del digitale terrestre.

### ISSUE THREAD

**Issue by infid0** [WorldLiveTV/WorldLiveTV.github.io#18]
Dato che _WLTV_ usa _PVR IPTV Simple Client_ e visto che su quest'ultimo si possono usare contemporaneamente sia i canali tv che quelli radio, mi domandavo se si potessero aggiungere anche le radio FM che sul digitale terrestre sono presenti dal canale 700 al canale 799. Mi sono permesso di svolgere il lavoro, a voi tocca solo la decisione, la supervisione e in caso, copiare/incollare dentro la playlist del DTT. :3

#EXTINF:-1 radio="true" tvg-id="RaiRadio1.it" tvg-logo="https://i.imgur.com/PwrAjjU.png" tvg-chno="701" group-title="Informazione",Rai Radio 1
https://icestreaming.rai.it/1.mp3
#EXTINF:-1 radio="true" tvg-id="RaiRadio2.it" tvg-logo="https://i.imgur.com/sDQFRbb.png" tvg-chno="702" group-title="Intrattenimento",Rai Radio 2
https://icestreaming.rai.it/2.mp3
#EXTINF:-1 radio="true" tvg-id="RaiRadio3.it" tvg-logo="https://i.imgur.com/LXv259b.png" tvg-chno="703" group-title="Cultura",Rai Radio 3
https://icestreaming.rai.it/3.mp3
#EXTINF:-1 radio="true" tvg-id="RaiGRParlamento.it" tvg-logo="https://i.imgur.com/J35seAE.png" tvg-chno="704" group-title="Politica",Rai GR Parlamento
https://icestreaming.rai.it/7.mp3
#EXTINF:-1 radio="true" tvg-id="RaiIsoradio.it" tvg-logo="https://i.imgur.com/QMdKACD.png" tvg-chno="705" group-title="Informazione",Rai Isoradio
https://icestreaming.rai.it/6.mp3
#EXTINF:-1 radio="true" tvg-id="RaiRadio3Classica.it" tvg-logo="https://i.imgur.com/0QvrAL9.png" tvg-chno="706" group-title="Musica classica",Rai Radio 3 Classica
https://icestreaming.rai.it/5.mp3
#EXTINF:-1 radio="true" tvg-id="RaiRadioKids.it" tvg-logo="https://i.imgur.com/ND3fVgQ.png" tvg-chno="707" group-title="Bambini",Rai Radio Kids
https://icestreaming.rai.it/11.mp3
#EXTINF:-1 radio="true" tvg-id="RaiRadioLive.it" tvg-logo="https://i.imgur.com/3QFrLIh.png" tvg-chno="708" group-title="Musica varia",Rai Radio Live
https://icestreaming.rai.it/10.mp3
#EXTINF:-1 radio="true" tvg-id="RaiRadioTechete.it" tvg-logo="https://i.imgur.com/JhXYBO8.png" tvg-chno="709" group-title="Vintage",Rai Radio Techete'
https://icestreaming.rai.it/9.mp3
#EXTINF:-1 radio="true" tvg-id="RaiRadioTuttaItaliana.it" tvg-logo="https://i.imgur.com/BgbWMbN.png" tvg-chno="710" group-title="Musica italiana",Rai Radio Tutta Italiana
https://icestreaming.rai.it/4.mp3
#EXTINF:-1 radio="true" tvg-id="RaiRadio1Sport.it" tvg-logo="https://i.imgur.com/aXpMAHl.png" tvg-chno="711" group-title="Sport",Rai Radio 1 Sport
https://icestreaming.rai.it/13.mp3
#EXTINF:-1 radio="true" tvg-id="NoNameRadio.it" tvg-logo="https://i.imgur.com/q9fY9jc.png" tvg-chno="712" group-title="Musica indie",No Name Radio powered by Rai
https://icestreaming.rai.it/15.mp3
#EXTINF:-1 radio="true" tvg-id="RadioCapital.it" tvg-logo="https://i.imgur.com/pPpti29.png" tvg-chno="713" group-title="Musica contemporanea",Radio Capital
https://4c4b867c89244861ac216426883d1ad0.msvdn.net/radiocapital/radiocapital/master_ma.m3u8
#EXTINF:-1 radio="true" tvg-id="RadioDeejay.it" tvg-logo="https://i.imgur.com/QErU7j6.png" tvg-chno="714" group-title="Musica contemporanea",Radio Deejay
https://4c4b867c89244861ac216426883d1ad0.msvdn.net/radiodeejay/radiodeejay/master_ma.m3u8
#EXTINF:-1 radio="true" tvg-id="RadioM2O.it" tvg-logo="https://i.imgur.com/tj6cgws.png" tvg-chno="715" group-title="Dance",Radio m2o
https://4c4b867c89244861ac216426883d1ad0.msvdn.net/radiom2o/radiom2o/master_ma.m3u8
#EXTINF:-1 radio="true" tvg-id="RadioVaticanaItalia.va" tvg-logo="https://i.imgur.com/aIAyP7g.png" tvg-chno="733" group-title="Religione",Radio Vaticana Italia
https://radio.vaticannews.va/stream-it
#EXTINF:-1 radio="true" tvg-id="RTL1025.it" tvg-logo="https://i.imgur.com/OdwMj6L.png" tvg-chno="736" group-title="Hits",RTL 102.5
https://streamingv2.shoutcast.com/rtl-1025
#EXTINF:-1 radio="true" tvg-id="RadioItaliaSMI.it" tvg-logo="https://i.imgur.com/1q59Bbi.png" tvg-chno="770" group-title="Musica italiana",Radio Italia SMI
https://radioitaliasmi.akamaized.net/hls/live/2093120/RISMI/master.m3u8
#EXTINF:-1 radio="true" tvg-id="R101.it" tvg-logo="https://i.imgur.com/3R8OhcY.png" tvg-chno="771" group-title="Musica contemporanea",Radio 101
https://icy.unitedradio.it/r101
#EXTINF:-1 radio="true" tvg-id="RMC.it" tvg-logo="https://i.imgur.com/X8VzKQF.png" tvg-chno="772" group-title="Musica contemporanea",Radio Monte Carlo
https://icy.unitedradio.it/RMC.mp3
#EXTINF:-1 radio="true" tvg-id="Radio105.it" tvg-logo="https://i.imgur.com/RtMxuH8.png" tvg-chno="785" group-title="Hits",Radio 105
https://icy.unitedradio.it/Radio105.mp3
#EXTINF:-1 radio="true" tvg-id="VirginRadio.it" tvg-logo="https://i.imgur.com/6LjCOKD.png" tvg-chno="786" group-title="Rock",Virgin Radio
https://icy.unitedradio.it/Virgin.mp3
#EXTINF:-1 radio="true" tvg-id="RadioMaria.it" tvg-logo="https://i.imgur.com/DHNa9Gq.jpg" tvg-chno="789" group-title="Religione",Radio Maria Italia
http://dreamsiteradiocp.com:8092/stream

**Comment by pandvan** [comment]
Grazie per la condivisione e il lavoro di ricerca degli stream.
Al momento non abbiamo previsione di inserire canali radiofonici (solo audio) sulla lista denomitata _DTT_
Puoi accedere a diversi di questi canali mediante la lista _Radio_.

Per avere accesso ad entrambe, puoi creare una lista "custom" selezionando _DTT_ e _Radio_
Avrai così accesso agli stream audio/video dalla sezione TV e quelli solo audio dalla sezione Radio.

**Comment by pandvan** [comment]
@infid0 Aggiornamento.
Stiamo valutando se creare una lista ad-hoc per i canali radiofonici (solo audio) di DTT e Tivusat.
Seguiti sui nostri canali per maggiori informazioni.

**Comment by infid0** [comment]
Ciao @pandvan sì ho notato che lo avete messo sotto forma di playlist opzionale, io mi ci sono fatto il mix personalizzato TV+Radio. Ma ho notato che RTL 102.5 è al canale 870 anziché al 736, forse a causa di un conflitto? A parte questo finalmente la sezione "Radio" di PVR IPTV Simple Client non è più una tristezza di landa desolata. Grazie! :3
_P.S. Scusate se mi sono fatto sentire solamente ora, ma avevo la verifica a due passaggi di Github su una mail Libero che come ormai tutti sapranno, ha avuto problemi per tutta la settimana._ :|
