### ISSUE TITLE
Canali lista Campania da aggiornare

### ISSUE THREAD

**Issue by xiaosal** [WorldLiveTV/WorldLiveTV.github.io#19]
Segnalo la necessità di aggionamento link/loghi di alcuni canali della lista Campania.

Canale 21

streaming: https://www.canale21.it/campania/
logo: OK quello che c'è

Tele A

streaming: https://palpro.it/telea/
logo: https://www.teleatv.it/wp-content/uploads/2022/02/TeleA.png

Canale 8 (probabilmente il link dello streaming che avete è corretto, ma vi chiedo gentilmente un check)

streaming: http://www.canaleotto.it/
logo: https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/C8_Logo_2015-01.png/800px-C8_Logo_2015-01.png

grazie

**Comment by pandvan** [comment]
Link agli stream dei canali indicati

Canale 21: https://0ff9dd7fe9b64bc08a5fc4ed525454c3.msvdn.net/live/S38994111/B7j0ql4XaZtE/playlist.m3u8
Tele A: https://lostream.it/hls/telea/video.m3u8
Canale 8: https://cdn3.streamshow.it/cloud-canale8/canale8/playlist.m3u8
Canale 8 è cane, perché quando non smettono non c'è un video nero, ma viene dato un HTTP404 forbidden

**Comment by pandvan** [comment]
@CrAcK75 per i loghi, credo sia lavoro per EPG.
Lasio a te.

**Comment by xiaosal** [comment]
Ok ho testato e canale 21 e tele A sono ok. Per canale 8 aspetto che trasmettano. Per i loghi quelli che ho segnalato hanno sfondo trasparente rispetto a quelli che ci sono adesso a sfondo bianco.

**Comment by CrAcK75** [comment]
> @CrAcK75 per i loghi, credo sia lavoro per EPG. Lascio a te.

per i regionali al momento vale il tvg-logo direttamente in lista... 

ma per questo Canale8 si è capito quando si può controllare? sul sito dice solo durante i live ma .... quando sono sti live??
effettivamente c'è la cdn3 al momento che però è video nero

**Comment by xiaosal** [comment]
Per canale 8 purtroppo è da un po' che non trasmettono. Domani sera controllo poiché in genere il lunedì sera trasmettevano sempre. Approfitto per segnalarvi anche televomero che non funziona più mentre sul sito funziona. Grazie

**Comment by xiaosal** [comment]
Ok. Comunque Canale 8 funziona. Adesso sta trasmettendo e si vede. 
Manca la parte dei loghi e poi si può chiudere.

**Comment by pandvan** [comment]
Loghi aggiornati come da richiesta.
Chiudo.

**Comment by xiaosal** [comment]
Testato i loghi e si vedono correttamente. thx
