### ISSUE TITLE
Aggiungere BOM Channel (canale 68) alla lista FTA

### ISSUE THREAD

**Issue by francescorosi27** [WorldLiveTV/WorldLiveTV.github.io#2]
L'URL al file M3U è questo: https://5f22d76e220e1.streamlock.net/BOMCHANNEL/BOMCHANNEL/playlist.m3u8

**Comment by CrAcK75** [comment]
anche questo lo inseriamo presto, sai dirci che tipo di canale è? credo sia un regionale ma di quale regione?

**Comment by francescorosi27** [comment]
Non è un canale regionale, è nazionale. E comunque è un canale per la maggior parte "musicale".

**Comment by CrAcK75** [comment]
il canale è stato inserito, al momento è tra i vari ed è classificato come canale di Moda Shopping poichè ogni volta che lo apro fanno solo televendite... in seguito possiamo sempre modificarlo
