### ISSUE TITLE
NSL TV Lazio da rivedere

### ISSUE THREAD

**Issue by CrAcK75** [WorldLiveTV/WorldLiveTV.github.io#22]
DIRETTA TV CANALE 88 DTT

https://www.nslradiotv.it/diretta-tv-canale-88-dtt/

**Comment by pandvan** [comment]
Richiede un broadcaster dedicato.
Non risulta usare un servizio "noto".

**Comment by Angeloblu83** [comment]
Ho provato dal loro sito ed esce questo messaggio quando vado a riprodurre 
![IMG_20230227_084938_896](https://user-images.githubusercontent.com/119079596/221507742-0fe0c8e5-9af0-4b5f-9530-0ea65a7031c2.jpg)

**Comment by pandvan** [comment]
Grazie.
Abbiamo le informazioni necessarie.
Necessita di uno sviluppo che va messo in coda

**Comment by CrAcK75** [comment]
Disponibile con la prossima versione dell'addon

**Comment by CrAcK75** [comment]
Fixed
