### ISSUE TITLE
Canali da aggiornare puglia 

### ISSUE THREAD

**Issue by Angeloblu83** [WorldLiveTV/WorldLiveTV.github.io#24]
Segnalo da aggiornare tele radio erre  e telefoggia link vecchi non più funzionanti siti ufficiali tutto ok

**Comment by Reneee69** [comment]
Teleradioerre
https://59d7d6f47d7fc.streamlock.net/teleradioerre/teleradioerre/playlist.m3u8
Telefoggia
https://59d7d6f47d7fc.streamlock.net/telefoggia/telefoggia/playlist.m3u8

? possono essere ?

**Comment by pandvan** [comment]
Link allo stream aggiornato.
Grazie della segnalazione.
