### ISSUE TITLE
Segnalazione Antenna 3 Veneto link non funzionante

### ISSUE THREAD

**Issue by Reneee69** [WorldLiveTV/WorldLiveTV.github.io#25]
Potrebbe essere questo il link giusto ?
https://59d7d6f47d7fc.streamlock.net/antennatreveneto/antennatreveneto.stream/playlist.m3u8

Ciao

**Comment by pandvan** [comment]
Avendo la sede a pochi passi, vado a chiedere direttamente a loro 😄

**Comment by pandvan** [comment]
Link allo stream aggiornato.
Grazie della segnalazione.
