### ISSUE TITLE
Canali gruppo MS e ACI Sport non funzionanti

### ISSUE THREAD

**Issue by Reneee69** [WorldLiveTV/WorldLiveTV.github.io#27]
Ciao,
i canali in lista DTT 933-934-937-939-941 e 943 della Galassia MS TV non funzionano

**Comment by Reneee69** [comment]
Per ACI Sport ho trovato questo :

https://g4wlk6xpy23a-hls-live.mariatvcdn.it/acisporttv/b7a3464f8e2001314de9fefebf11229d.sdp/playlist.m3u8

**Comment by pandvan** [comment]
Aggiunto taccone temporaneo per ACI Sport
Da rivedere più ad alto livello.

**Comment by CrAcK75** [comment]
son rimasti attivi solo mssport, msmotor e aci, gli altri pare non esistano più al momento

**Comment by pandvan** [comment]
Anche e-ms è ancora vivo.
Sono passati a nuova vita con il lancio dell'applicazione dedicata MS+
