### ISSUE TITLE
Aggiungere Explorer HD Channel (canale 176 di Sky) alla lista FTA

### ISSUE THREAD

**Issue by francescorosi27** [WorldLiveTV/WorldLiveTV.github.io#3]
L'URL del file M3U è questo: https://59d7d6f47d7fc.streamlock.net/explorerhdch/explorerhdch/playlist.m3u8
È un canale su Sky, ma è FTA e c'è la live stream (gratis) sul sito ufficiale ([explorertv.it](https://explorertv.it)).

**Comment by CrAcK75** [comment]
perdonami non avevo visto l'issue ... grazie per la segnalazione

**Comment by CrAcK75** [comment]
canale aggiunto
