### ISSUE TITLE
Canale 5 non funzione 

### ISSUE THREAD

**Issue by dgl2128** [WorldLiveTV/WorldLiveTV.github.io#30]
https://paste.kodi.tv/jelapetaku

**Comment by dgl2128** [comment]
https://paste.kodi.tv/jelapetaku

**Comment by CrAcK75** [comment]
dal log si capisce solo che c'è un errore che non dovrebbe esserci... non si capisce perchè... potrebbe essere legato alla linea, a kodi o altro ... 

ti consiglio di entrare nel gruppo telegram [WorldLiveTv](https://t.me/worldlivetv) per interagire e cercare di capire cosa non va

**Comment by pandvan** [comment]
@dgl2128 ci sono stati progressi a seguito della tua segnalazione?
Se hai risolto il problema, procediamo con la chiusura.

**Comment by dgl2128** [comment]
> @dgl2128Has there been any progress following your report? If you have solved the problem, let's proceed with the closure.

Tutti I canale si vedono buono. Canale 5 non si vedo.

**Comment by dgl2128** [comment]
Si sono all estero io uso in VPN, posso fare qualcosa x 
 vedere canale 5 ? Grazie

**Comment by CrAcK75** [comment]
no nulla ... se fossi entrato nel gruppo avremmo fatto prima, il problema è la VPN ma non diamo supporto a riguardo perchè non ce nulla da fare. Non interferiamo con le regole delle emittenti se decidono di bloccare i contenuti all'estero.
