### ISSUE TITLE
Televomero non funzionante

### ISSUE THREAD

**Issue by pandvan** [WorldLiveTV/WorldLiveTV.github.io#34]
Si riprende da qui #19 

Link al sito: https://www.televomero.it/live-tv/
Hint: xdevel

**Comment by xiaosal** [comment]
Grazie. Ho provato ad estrarre il flusso m3u ed ho visto che è come se nell'URL ci fosse un token che cambia nel tempo. Quindi dopo circa 24h l'URL non è più valido.

**Comment by xiaosal** [comment]
Ho provato adesso e si vede.
