### ISSUE TITLE
Canale 58

### ISSUE THREAD

**Issue by github30000** [WorldLiveTV/WorldLiveTV.github.io#36]
Sarebbe possibile aggiungere nella lista dei regionali questo canale?

https://www.canale58.com/streaming-new.php

Grazie

**Comment by pandvan** [comment]
@github30000 In quali regioni trasmette? Disponibile nel digital terrestre?

**Comment by github30000** [comment]
E' a diffusione regionale, campania  per la precisione e si trova al canale 85 del digitale terrestre
Grazie
