### ISSUE TITLE
Canali WLTV AMICA9 TV ED EMMETV 

### ISSUE THREAD

**Issue by Giammmy77** [WorldLiveTV/WorldLiveTV.github.io#37]
Tra i canali tv presenti nella lista WLTV ci sono fra gli altri Amica9 TV (Puglia) ed emmeTv (Marche). Il primo non parte proprio schermo nero mentre il secondo fino a qualche tempo fa era visibile. Come fare per poter inserire nuovamente lo streaming di entrambe o almeno del primo? Grazie

**Comment by Reneee69** [comment]
EmmeTV
https://tna5.bozztv.com/emmetv89/index.m3u8

**Comment by Reneee69** [comment]
EMMETV
https://tna5.bozztv.com/emmetv89/index.m3u8

**Comment by CrAcK75** [comment]
> Amica9

riguardo Amica9 non c'è una diretta on line e, finchè non ci sarà qualcosa di costante, è difficile integrarlo perchè non sappiamo se c'è e da dove trasmette

**Comment by CrAcK75** [comment]
> emmeTv

questo url non è valido ma il canale sarà disponibile conla prossima hotfix

**Comment by CrAcK75** [comment]
Amica9 non abbiamo ancora trovato una diretta... chiudo, se si troverà si potrà aprire un'altra issue
