### ISSUE TITLE
Class CNBC

### ISSUE THREAD

**Issue by Reneee69** [WorldLiveTV/WorldLiveTV.github.io#39]
class CNBC
https://859c1818ed614cc5b0047439470927b0.msvdn.net/live/S57048752/8raQqCXozN1H/chunklist_b2628000.m3u8

**Comment by CrAcK75** [comment]
fixed with https://859c1818ed614cc5b0047439470927b0.msvdn.net/live/S57048752/8raQqCXozN1H/playlist.m3u8
