### ISSUE TITLE
World Live TV Helper error

### ISSUE THREAD

**Issue by LoryTurro** [WorldLiveTV/WorldLiveTV.github.io#4]
Quando provo ad accedere ad una canale televisivo Kodi da "error -5 while decompresing data: inconplete or truncated stream"

**Comment by CrAcK75** [comment]
detta così vuol dire tutto e niente, aggiorna l'addon alla 1.2.1, seleziona una nuova lista tipo la DTT, riavvia kodi e, se il problema si ripresenta possiamo parlarne su gruppo telegram https://t.me/worldlivetv
