### ISSUE TITLE
rsi la 1 e rsi la 2 

### ISSUE THREAD

**Issue by Martina3333** [WorldLiveTV/WorldLiveTV.github.io#45]
ciao amici di wltv,  potete aggiornare i canali rsi la 1 e rsi la 2 queli non stabili con questi che vengono tasmessi tramite il sito uaznao ora posto i link del sito rsi la 1 https://uaznao.com/rsi-la-1-in-diretta-streaming/ il link per rsi la 2 https://uaznao.com/rsi-la-2-in-diretta-streaming/ ciao.

**Comment by CrAcK75** [comment]
non sono funzionanti

**Comment by pandvan** [comment]
Dovrebbero essere funzionanti solo durante certi eventi "di interesse".
Quanto siano leciti non penso sia necessario scriverlo...
