### ISSUE TITLE
raitalia

### ISSUE THREAD

**Issue by Martina3333** [WorldLiveTV/WorldLiveTV.github.io#46]
ciao per che non mettere raitalia in wltv, il segnale e stabile da qualche anno come tutti i canali che 
 ci sono in wltv e poi e un canale rai anche se e per estero http://210.210.155.37/x6bnqe/s/s63/index2.m3u8 ciao

**Comment by CrAcK75** [comment]
è un sito pirata, non ci interessa, d'altronde si può vedere direttamente tutta la rai non serve per forza avere il canale che trasmette solo all'estero

**Comment by Martina3333** [comment]
ciao peccato che su wltv non si puo vedere raitalia, che poi che sia un canale per estero o per italia non cambiarebe niente per che la programmazione e diversa  dai canali  normale, ciao.
