### ISSUE TITLE
turkmenistan sport

### ISSUE THREAD

**Issue by Martina3333** [WorldLiveTV/WorldLiveTV.github.io#48]
ciao amici di wltv, nella lista di canali si puo mettere il canale sportivo turkmenistan sport anche se non e in lingua italiana trasmette tanto sport,   e anche le nostre partite di serie a  il canale e free, questo e il sito dove il canale trasmette in streaming https://turkmentv.gov.tm/page/6/?from=4  ciao

**Comment by Martina3333** [comment]
il canale e free

**Comment by CrAcK75** [comment]
mi spiace.. i canali esteri hanno una loro sezione non gestita da noi direttamente e non inseriremo canali tra quelli italiani
