### ISSUE TITLE
Food Network ha smesso di funzionare

### ISSUE THREAD

**Issue by francescorosi27** [WorldLiveTV/WorldLiveTV.github.io#5]
Discovery ha appena spento lo streaming di Food Network con il link non-Discovery+ (https://sbshdlu5-lh.akamaihd.net/i/sbshdl_6@1000854/master.m3u8), ma ovviamente su Discovery+ funziona ancora, quindi potreste aggiungere Food Network alla API di Discovery+?

**Comment by WorldLiveTV** [comment]
Food Network non ha alcun problema sull'addon, non ci risulta abbia spento lo stream

**Comment by francescorosi27** [comment]
Scusate, ho visto che il link su https://tvchannels.worldtvlive.eu/tv/fta era quello vecchio e ho pensato che non funzionasse anche su Kodi. Chiudo. (e poi, mi potreste spiegare perché funziona su Kodi anche se sul sito mostra il link vecchio?)

**Comment by WorldLiveTV** [comment]
Non è un link pubblico, fa parte di vecchie prove e verrà presto dismesso... si può usare solo l'addon
