### ISSUE TITLE
Canali discovery da rivedere 

### ISSUE THREAD

**Issue by Angeloblu83** [WorldLiveTV/WorldLiveTV.github.io#50]
Non su tutti i dispositivi ma si presentano ancora problemi di squadrettamenti o blocco dopo alcuni minuti da ricontrollare appena possibile

**Comment by CrAcK75** [comment]
Non dipende da noi, per cui non possiamo rivedere nulla, devo solo tentare un altro approccio per mandare in play i canali ma è solo un tentativo, non è detto che si risolva visto che dipende da Input stream adaptive.

**Comment by CrAcK75** [comment]
al momento nessun problema da segnalare, chiudo
