### ISSUE TITLE
Videoregione (Emilia Romagna)

### ISSUE THREAD

**Issue by nocelab** [WorldLiveTV/WorldLiveTV.github.io#51]
È possibile inserire Videoregione del canale DTT 99 (zona Cesena)?
https://videoregione.it/#web-tv

**Comment by CrAcK75** [comment]
inserito, sarà disponibile entro 2 ore  o max  domani

**Comment by nocelab** [comment]
segnalo che non è più raggiungibile il canale... da errore all'apertura
