### ISSUE TITLE
Tvi Molise 

### ISSUE THREAD

**Issue by Giammmy77** [WorldLiveTV/WorldLiveTV.github.io#57]
Tvi Molise non visibile

**Comment by pandvan** [comment]
Stream non funzionante nel loro sito. C'è poco che possiamo fare noi.
Cortesemente, prima di aprire una segnalazione, controllate sempre prima che la trasmissione stia funzioando.

**Comment by Giammmy77** [comment]
sarà fatto. chiedo scusa

**Comment by pandvan** [comment]
Nessun problema :+1:

**Comment by CrAcK75** [comment]
Lasciamo aperta la issue per un po'... Magari sul sito si riprende e vediamo se riusciamo ad inserirlo

**Comment by CrAcK75** [comment]
lo stream ha ripreso a funzionare sul sito e di conseguenza anche su WLTV, chiudo
