### ISSUE TITLE
mancanza canale retemia sulla lista regionali

### ISSUE THREAD

**Issue by tresi800** [WorldLiveTV/WorldLiveTV.github.io#60]
Salve piacere marco,non trovo retemia nella lista regionali, esiste via web

**Comment by CrAcK75** [comment]
Puoi indicare qui il sito web?

**Comment by tresi800** [comment]
https://www.retemia.eu/guarda-retemia/

Questo è il sito

Il gio 11 gen 2024, 08:03 CrAcK75 ***@***.***> ha scritto:

**Comment by CrAcK75** [comment]
retemia è presente da oltre 1 anno nei regionali (regione toscana), ed è funzionante
