### ISSUE TITLE
telerent 7gold 

### ISSUE THREAD

**Issue by Diabolik33** [WorldLiveTV/WorldLiveTV.github.io#62]
ciao si puo inserire di nuovo il canale telerent 7 gold il link e questo qui https://stream7.xdevel.com/video3s86-2136/stream/playlist.m3u8 ciao

**Comment by CrAcK75** [comment]
serve il sito ufficiale di partenza

**Comment by Diabolik33** [comment]
il sito e questo https://www.telerent.net il link e stato preso dal segnale in HbbTV
