### ISSUE TITLE
rtv san marino tv  e rtv san marino tv spot

### ISSUE THREAD

**Issue by Diabolik33** [WorldLiveTV/WorldLiveTV.github.io#63]
ciao in questo momento nel wltv i canali rtv san marino tv, e rtv san marino tv sport, non si vedono, dice siamo spiacenti il canale selezionato non e disponibile invece dal sito si vedono, il sito e questo qui, https://www.sanmarinortv.sm  ripristinare a più presto ciao.

**Comment by CrAcK75** [comment]
si sistemeranno al prossimo hotfix ma probabile bisognerà attendere comunque la fix di inputstream adaptive

**Comment by Diabolik33** [comment]
i canali rtv san marino e rtv san marino tv sport, per il momento li vedo dalla lista dei canali stranieri e li o messi nei canali preferiti ciao.
