### ISSUE TITLE
ciao usa 

### ISSUE THREAD

**Issue by Diabolik33** [WorldLiveTV/WorldLiveTV.github.io#64]
non si vede su wltv ciao usa ma dal sito si, il sito e questo https://ciaousa.tv  ciao.

**Comment by Diabolik33** [comment]
> non si vede su wltv ciao usa ma dal sito si, il sito e questo https://ciaousa.tv la pagina dove si vede il canale e questa https://ciaousa.tv/watch-live/ciao-usa-tv ciao.

**Comment by CrAcK75** [comment]
aggiunto tra i canali vari e disponibile con la prossima hotfix 12118

**Comment by Diabolik33** [comment]
non si vede tramite wltv il canale ciao usa ma nel sito si si può ripristinare ciao.
