### ISSUE TITLE
tele radio sciacca 

### ISSUE THREAD

**Issue by Diabolik33** [WorldLiveTV/WorldLiveTV.github.io#65]
ciao amici di wltv devo comunicare che, il canale tele radio sciacca, CHIUDE DOPO OLTRE 40 ANNI- TELE RADIO SCIACCA – LA LETTERA DELLA PROPRIETÀ É terminata in queste ore una lunga avventura durata oltre 40 anni chiamata Tele Radio Sciacca.

Sono stati più di quarant’anni fatti di informazione, spettacolo, cultura e intrattenimento in un contesto cittadino che ha meritato di essere raccontato con dettaglio, attenzione e rispetto.

Tele Radio Sciacca interrompe le trasmissioni con dolore al termine di una lenta ma inesorabile agonia, iniziata a causa di scelte scriteriate prese da governanti che hanno preferito tutelare interessi personali e partitici, piuttosto che tenere in vita la libertà di pensiero, la comunicazione indipendente e la democrazia.

Tele Radio Sciacca interrompe le trasmissioni anche a causa dell’evoluzione del mondo della comunicazione sempre più attento a propinare contenuti mordi e fuggi distruggendo invece l’informazione sana e approfondita.

Per raccontare di ciò che è stato non basterebbe un libro intero. Per questo non ci dilungheremo, ma permetteteci soltanto di ringraziare tutti coloro i quali hanno scritto anche la più piccola pagina nella storia di questa emittente locale che per anni è stata un punto di riferimento cittadino, provinciale e regionale.

Un ringraziamento infine a tutti i telespettatori che, in questo lunghissimo periodo, hanno deciso di seguire la programmazione della nostra emittente.

Siamo orgogliosi di essere stati ospiti, per oltre 40 anni, delle vostre case.

Nuccy Piro, quindi si puo togliere da wltv ciao.

**Comment by CrAcK75** [comment]
... chiudo
