### ISSUE TITLE
video mediteraneo 

### ISSUE THREAD

**Issue by Diabolik33** [WorldLiveTV/WorldLiveTV.github.io#67]
su wltv il canale video mediteraneo non si vede e nel sito si vede, il sito e questo https://www.videomediterraneo.it/ il link del canale e https://streamcdnb3-bfbe5f347ac4424faf719dda285bc39e.msvdn.net/live/S54897858/4gWO7tTzpK3N/chunklist_b2096000.m3u8 ciao.

**Comment by CrAcK75** [comment]
i link non è quello ma è stato fixato
