### ISSUE TITLE
rete mia 

### ISSUE THREAD

**Issue by Diabolik33** [WorldLiveTV/WorldLiveTV.github.io#68]
nel wltv ce di ripristinare  il canale rete mia  il sito e questo https://www.retemia.eu/ il link del canale questo https://5db313b643fd8.streamlock.net/rete/rete/chunklist_w1770650038.m3u8 ciao

**Comment by pandvan** [comment]
Link aggiornato.
Sarà disponibile su World Live TV a partire da domani.

Grazie per la segnalazione.
