### ISSUE TITLE
Messaggio di errore 

### ISSUE THREAD

**Issue by campe983** [WorldLiveTV/WorldLiveTV.github.io#69]
Ciao a tutti, scrivo qui per la prima volta.
Utilizzo l add on World Live TV Helper da diversi anni senza alcun problema su due diversi dispositivi Fire Stick. Ora su uno di essi, da un paio di mesi, ogni volta che provo ad avviare il componente aggiuntivo, ricevo il seguente messaggio di errore:

"World Live TV Helper error, please check the log for more information"

L'altro dispositivo funziona ancora correttamente.

La versione di KODI è 19.1.

Ho provato a cancellare cache --> nessun risultato
Ho provato a cancellare i dati e a reinstallare il componente aggiuntivo --> nessun risultato

Qualche suggerimento?

Qualsiasi aiuto sarebbe molto apprezzato!

**Comment by CrAcK75** [comment]
Metti Kodi 20 e, se possibile, con installazione pulita e riprova

**Comment by CrAcK75** [comment]
in mancanza di feedback ... chiudo
