### ISSUE TITLE
rai play 

### ISSUE THREAD

**Issue by Diabolik33** [WorldLiveTV/WorldLiveTV.github.io#79]
in lista ce di aggiornare i canali  rai play 1, 2, 3  in wltv i tre canali dicono wltv helper siamo spiacenti il canale selezionato non e disponibile,  nel sito rai play 1 da un immagine fissa da dove sarà trasmesso il commento in italiano del Eurovision Song Contest, su rai play 2 e da ieri che ce il giro di italia senza  pubblicità, rai play 3 per il momento non trasmette niente ma e pure da aggiornare https://www.raiplay.it .

**Comment by CrAcK75** [comment]
non c'è nulla da aggiornare, se sul sito non c'è nulla anche wltv non avrà nulla da mostrare

**Comment by pandvan** [comment]
Su Rai Play (applicazione e HbbTV) sono comparsi anche i canali Ray Play Sport 1, 2 e 3
Non sono lineari, trasmettono solo eventi in caso i canali lineri siano già occupati.

**Comment by CrAcK75** [comment]
chiudo
