### ISSUE TITLE
Il menu "Seleziona lista" non si apre

### ISSUE THREAD

**Issue by LoxoSoftware** [WorldLiveTV/WorldLiveTV.github.io#8]
Su Kodi per Debian (v19) l'addon helper si installa correttamente ma non si apre il menu "Seleziona lista".

**Comment by CrAcK75** [comment]
E' una delle funzioni fondamentali dell'addon che usano praticamente tutti, fino ad oggi non abbiamo mai riscontrato questo problema, controlla che la versione dell'addon sia l'ultima (ad oggi la 1.2.5, con hotfix 1004), riavvia kodi e riprova. 
Ti invitiamo a contattarci sul gruppo Telegram per avere un'interazione maggiore https://t.me/worldlivetv
