### ISSUE TITLE
Channels Italian not start 

### ISSUE THREAD

**Issue by Andreina57** [WorldLiveTV/WorldLiveTV.github.io#83]
Hi the Chanel Italian not working

**Comment by Kenjo36** [comment]
> Hi the Chanel Italian not working

**Comment by CrAcK75** [comment]
Please provide more details because the addon it's working perfectly to us. WLTV is an italian addon designed to work only in Italy without any VPN

**Comment by erbarto** [comment]
I have the same problem. I'm in Italy too.
When I try to start a channel, I get an information saying "failed playback of one or more elements, check the logo for more information about this message". I have looked in the log but can't find anything useful.

**Comment by CrAcK75** [comment]
To date WLTV works well on Kodi 21, if you follow us on telegram https://t.me/worldlivetv you can read everything in the staff announcements section. I was forced to publish a version to solve the problem of the Discovery channels and this broke the compatibility with Kodi20 which is in the process of being resolved, the advice is to follow us on telegram by reading the announcements on the group and on the channel. As well as always keeping Kodi updated to the latest official version.

**Comment by Andreina57** [comment]
HI
After today's worldlivetv update everything seems to be working.
Thank you
I use two Firesticks with Kodi version 20 and one version 21
Good job.

[image: Icona di Verificata con community]
------------------------------


Il dom 16 giu 2024, 12:17 CrAcK75 ***@***.***> ha scritto:

**Comment by Andreina57** [comment]
HI
After today's worldlivetv update everything seems to be working.
Thank you
I use two Firesticks with Kodi version 20 and one version 21
Good job.

**Comment by erbarto** [comment]
Mine too. After update to Kodi 21 It works perfectly.

**Comment by Andreina57** [comment]
Hi I have same errors whit discoveri Chanel, dmax etc etc
Kod121
Fire stick
Best regards
