### ISSUE TITLE
Problem with rai 3 lombardia

### ISSUE THREAD

**Issue by ftagliani** [WorldLiveTV/WorldLiveTV.github.io#88]
or a month now you can't see rai 3 lombardia, or rather you can't see it well. what's the cause? who can you contact?

**Comment by CrAcK75** [comment]
the regional video stream starts only if you select the RAI3 channel a few seconds after the start of the TGR live broadcast, of course you must have set your region from the settings

**Comment by CrAcK75** [comment]
no feedback ... close
