### ISSUE TITLE
Televomero lista Campania 

### ISSUE THREAD

**Issue by xiaosal** [WorldLiveTV/WorldLiveTV.github.io#89]
Lo streaming di Televomero, nella lista Campania, non funziona più.
Online funziona:
https://www.televomero.it/live-tv/

Inoltre volevo chiedere se fosse possibile spostare telecapri (sempre lista Campania) da Twitch a YouTube poiché funziona meglio. Su Twitch prende spesso l'errore "playback failed".
Grazie

**Comment by CrAcK75** [comment]
sarà disponibile con la prossima hotfix (v121209)
