### ISSUE TITLE
[Test] Rai4k 

### ISSUE THREAD

**Issue by campipaolo** [WorldLiveTV/WorldLiveTV.github.io#9]
Rai4k non si avvia 
Kodi 19.4, Motorola g22 Android 12

Di seguito link log 

https://paste.kodi.tv/caxogoneto

**Comment by Angeloblu83** [comment]
Canali regionali che non si avviano : video33 trentino (vb33) , video mediterraneo (Sicilia) , video star (Sicilia)

**Comment by Angeloblu83** [comment]
Preciso anche come già segnalato qualche giorno fa di aggiungere nei regionali tele campione sport presente live streaming sul sito publirose

**Comment by CrAcK75** [comment]
Rai 4K ripristinato
