### ISSUE TITLE
telenuova pagani (salerno)

### ISSUE THREAD

**Issue by Giammmy77** [WorldLiveTV/WorldLiveTV.github.io#90]
si potrebbe inserire telenuova pagani raggiungibile all' indirizzo telenuovapuntotv? diretta streaming al seguente link. grazie

**https://platform.wim.tv/#/webtv/Telenuova/live/a634d9b6-9e30-4cd9-a21d-307a2fb3b75e**

**Comment by CrAcK75** [comment]
sarà disponibile con la prossima hotfix (v121209), il canale però non sembra essere stabile sul sito di appartenenza, potrebbe non avviarsi sempre
