### ISSUE TITLE
Lombardia, Mantova, Telemantova

### ISSUE THREAD

**Issue by jambolo1970** [WorldLiveTV/WorldLiveTV.github.io#94]
Buona sera team,
Volevo sapere se era possibile aggiungere alla lista del digitale terrestre anche Telemantova
https://5ce9406b73c33.streamlock.net/TeleMantova/livestream/playlist.m3u8
sarebbe sul 77 o sul 277.
Vedo meglio e tutti i canali con voi che con l'antenna.

**Comment by CrAcK75** [comment]
il canale è presente dal 2021 nella lista dei regionali
